### PR TITLE
Added a few clarifying pieces of info

### PR DESCRIPTION
**Pull request by dougtoppin**
I added a little about the ELB healthcheck and a couple of entries to the FAQ that might be helpful to someone unfamiliar.

### CODE REVIEW

**Comment by nicolaka** [comment]
@dougtoppin thanks for the PR! I spent some time last week adjusting the cloudformation to address some of your concerns. Now we've added nginx+interlock containers on each UCP node and they're listening on port 80. More info on how they can be used can be found in the readme on master. There is no need to adjust the healthcheck at this point as it will work automatically with port 80. This will make sure that you can easily deploy your applications. 

If you can please please rebase and adjust PR so I can merge.

**Comment by dougtoppin** [comment]
Sure, will do. Should be a new PR in the next couple of days. Tks for the DDC quickstart repo work. The quickstart CF approach worked well for me.

**Comment by dougtoppin** [comment]
I just started the DDC up again and still see no healthy ucp instances. If I check a node I do not see anything other than ucp-swarm-join and ucp-proxy containers running.
I used the launch button from your MD. Should the healthcheck containers be running
or has the CF template that I'm using not been updated with your changes yet?
When you said "readme on master" where did you mean?

**Comment by nicolaka** [comment]
@dougtoppin this is expected. I didn't update the template in the links yet as we're waiting for test results. For now, you can easily upload the ddc_on_aws.json directly.

**Pull request closed without merging**
